### ISSUE TITLE
MainPage

### ISSUE THREAD

**Issue by TaeUk471** [sprint-part2-team14/OpenMind#31]
### 기능명
메인 페이지

### 구현 목표
- [x] 이름을 입력하고 “질문 받기” 버튼을 클릭하면 피드를  생성합니다. 
- [x] 피드 생성 응답을 받으면 응답으로 받은 피드 id를 활용해  “/post/{id}/answer” 페이지로 이동합니다.

### 담당자
한태욱

**Comment by byunjiin** [comment]
MainPage 리팩토링 완료했습니다.
