### ISSUE TITLE
Modal 페이지

### ISSUE THREAD

**Issue by TaeUk471** [sprint-part2-team14/OpenMind#58]
### 기능명
Modal 페이지

### 구현 목표
- [x] 모달의 X 버튼, 모달 내용을 벗어난 부분을 클릭하면 모달을 닫습니다.
- [x] 모달에 질문 내용이 없는 경우 “질문 보내기” 버튼은  비활성화 상태입니다. 질문 내용이 있는 경우 활성화 됩니다.

### 담당자
한태욱

**Comment by byunjiin** [comment]
ModalPage 리팩토링 완료했습니다.
