### ISSUE TITLE
컴포넌트 폴더 구조 변경에 따른 경로 수정

### ISSUE THREAD

**Issue by TaeUk471** [sprint-part2-team14/OpenMind#64]
### 기능명
컴포넌트 폴더 구조 변경에 따른 경로 수정

### 구현 목표
- [ ] 컴포넌트 폴더 구조 변경에 따른 경로를 전부 수정한다.

### 담당자
한태욱

### 특이사항
대체 왜!!! 이게 이렇게 된거냐!

**Comment by byunjiin** [comment]
컴포넌트 구조 수정했습니다.
