### ISSUE TITLE
전체 CSS 수정

### ISSUE THREAD

**Issue by elenfl0122** [sprint-part2-team14/OpenMind#91]
### 기능명
- css refactoring

### 구현 목표
- [x] 주석 제거
- [x] console.log 제거
- [x] text-area 수정
- [x] userCard 아이디 길이 조정
- [x] submit 버튼 form 태그 안에 넣어주기
- [x] 전체 css 레이아웃 수정

### 담당자
- 이지수

**Comment by byunjiin** [comment]
전체 CSS 수정했습니다
